name: BET-AI

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:

  bet-ai:

    runs-on: ubuntu-latest

    steps:

      - name: Baixar código
        uses: actions/checkout@v4


      - name: Configurar Python
        uses: actions/setup-python@v5

        with:
          python-version: "3.11"


      - name: Instalar dependências
        run: |

          python -m pip install --upgrade pip

          pip install requests


      - name: Verificar configuração
        env:
          API_FOOTBALL_KEY: ${{ secrets.API_FOOTBALL_KEY }}

        run: |

          python -c "import os; key=os.getenv('API_FOOTBALL_KEY'); assert key, 'ERRO: API_FOOTBALL_KEY não encontrada'; print('API_FOOTBALL_KEY configurada corretamente.')"


      - name: Executar BET-AI
        env:
          API_FOOTBALL_KEY: ${{ secrets.API_FOOTBALL_KEY }}

        run: |

          python main.py
